In [4]:
# List 
# List는 모두 우리 pc의 list에 저장이 된다. 
my_1 = [2,1,5,4,3]
my_12 = [12,21,35,44,53]
print(my_1)
print(my_1[1])
print(my_1+my_12)
print(my_1*2)
new_lst = []
for i in my_1:
    # print(i*2)
    new_lst.append(i*2)
print(new_lst)

[2, 1, 5, 4, 3]
1
[2, 1, 5, 4, 3, 12, 21, 35, 44, 53]
[2, 1, 5, 4, 3, 2, 1, 5, 4, 3]
[4, 2, 10, 8, 6]


In [5]:
import numpy as np

In [6]:
my_list = [0,1,2,3,4,5,6,7,8,9]
print(type(my_list))

<class 'list'>


In [8]:
ar = np.array(my_list)
print(type(ar))

<class 'numpy.ndarray'>


In [9]:
print(ar)
print(type(ar))
print(my_list)
print(type(my_list))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [10]:
print(type(my_list))

<class 'list'>


In [11]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
al = [1,2,3]
bl = [4,5,6]
print(al + bl)

[1, 2, 3, 4, 5, 6]


In [14]:
al = [1,2,3]
bl = [4,5,6]
aa = np.array(al)
ba = np.array(bl)
print(aa+ba)

[5 7 9]


In [15]:
data = [0,1,2,3,4,5,6,7,8,9]
x = np.array(data)
print(x)
x

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(2 * x)

[ 0  2  4  6  8 10 12 14 16 18]


In [18]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2*a)
print((2*a)+b)

[2 4 6]
[12 24 36]


In [19]:
a_L = [1,2,3]
b_L = [10,20,30]
2 * a_L + b_L

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [21]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [22]:
print(a == 2)

[False  True False]


In [23]:
print(b > 10)

[False  True  True]


In [26]:
print((a == 2) & (b > 10))

[False  True False]
