In [1]:
# 넘파이의 자료형
import numpy as np

In [2]:
import numpy as np

a = np.array([1.0, 2.0, -3.0, 0.0])
b = np.array([0.0, 1.0, 0.0, 0.0])
c = a / b

print(c)

[ inf   2. -inf  nan]


/var/folders/k1/p1ftl_jn2ms_y291k82cwb1c0000gn/T/ipykernel_55287/2309270616.py:5: RuntimeWarning: divide by zero encountered in divide
  c = a / b
/var/folders/k1/p1ftl_jn2ms_y291k82cwb1c0000gn/T/ipykernel_55287/2309270616.py:5: RuntimeWarning: invalid value encountered in divide
  c = a / b


In [3]:
a = np.zeros(5)
a.dtype

dtype('float64')

In [4]:
a

array([0., 0., 0., 0., 0.])

In [5]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [7]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [9]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d[3] = "가나다라마"
d

array(['abc', 'abcd', 'ABCD', '가나다라', ''], dtype='<U4')

In [10]:
e = np.ones((2,3,4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [11]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [15]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.arange(10) # 0 .. n - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
np.linspace(0, 100, 11) 

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [23]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [20]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [27]:
# 전치 연산
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 배열의 크기 변형

In [29]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
x = np.arange(5)
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])