In [4]:
# List 
# List는 모두 우리 pc의 list에 저장이 된다. 
my_1 = [2,1,5,4,3]
my_12 = [12,21,35,44,53]
print(my_1)
print(my_1[1])
print(my_1+my_12)
print(my_1*2)
new_lst = []
for i in my_1:
    # print(i*2)
    new_lst.append(i*2)
print(new_lst)

[2, 1, 5, 4, 3]
1
[2, 1, 5, 4, 3, 12, 21, 35, 44, 53]
[2, 1, 5, 4, 3, 2, 1, 5, 4, 3]
[4, 2, 10, 8, 6]


In [1]:
import numpy as np

In [6]:
my_list = [0,1,2,3,4,5,6,7,8,9]
print(type(my_list))

<class 'list'>


In [8]:
ar = np.array(my_list)
print(type(ar))

<class 'numpy.ndarray'>


In [9]:
print(ar)
print(type(ar))
print(my_list)
print(type(my_list))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [10]:
print(type(my_list))

<class 'list'>


In [11]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
al = [1,2,3]
bl = [4,5,6]
print(al + bl)

[1, 2, 3, 4, 5, 6]


In [14]:
al = [1,2,3]
bl = [4,5,6]
aa = np.array(al)
ba = np.array(bl)
print(aa+ba)

[5 7 9]


In [15]:
data = [0,1,2,3,4,5,6,7,8,9]
x = np.array(data)
print(x)
x

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(2 * x)

[ 0  2  4  6  8 10 12 14 16 18]


In [18]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2*a)
print((2*a)+b)

[2 4 6]
[12 24 36]


In [19]:
a_L = [1,2,3]
b_L = [10,20,30]
2 * a_L + b_L

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [21]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [22]:
print(a == 2)

[False  True False]


In [23]:
print(b > 10)

[False  True  True]


In [26]:
print((a == 2) & (b > 10))

[False  True False]


In [2]:
# c = np.array([ [0,1,2] , [3,4,5]_ # 2 x 3 array
c = np.array([[0,1,2],[3,4,5]])
print(c)
c

[[0 1 2]
 [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
#행의 갯수
print(len(c))

2


In [4]:
# 열의 갯수
print(len(c[0]))

3


In [5]:
d = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]]) # 2 x 3 x 4 array

In [13]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [14]:
print(d.ndim) # 차원 
print(d.shape) # 차원 내부 갯수 순서 

3
(2, 3, 4)


In [11]:
a = np.array([[10,20,30,40],[50,60,70,80]])
print(a.ndim)
print(a.shape)

2
(2, 4)


In [16]:
a = np.array([[0,1,2,], [3,4,5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [19]:
print(a[0,0])
print(a[0,1])
print(a[-1,-1])

a = np.array([[0,1,2,], [3,4,5]])
a

0
1
5


array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
print(a[0,0])

0


In [21]:
# 배열 슬라이싱

a = np.array( [ [0,1,2,3],
                [4,5,6,7]  ])

a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
a[0, :]

array([0, 1, 2, 3])

In [23]:
a[:, 0:2]

array([[0, 1],
       [4, 5]])

In [24]:
a[:, 1]

array([1, 5])

In [25]:
a[1, 1:]

array([5, 6, 7])

In [26]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [27]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [45]:
print(m[1, 2])

7


In [46]:
print(m[2, 4])
print(m[-1,-1])

14
14


In [52]:
print(m[1:2, 1:3])
print(m[1, 1:3])

[[6 7]]
[6 7]


In [53]:
print(m[1:, 2])

[ 7 12]


In [50]:
print(m[:2, 3:])
print(m[0:2,3:5])

[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


In [54]:
# 배열 인덱싱

import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])

print(a)
print(idx)
print(a[idx])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [55]:
print(a % 2)

[0 1 0 1 0 1 0 1 0 1]


In [56]:
print(a % 2 == 0)

[ True False  True False  True False  True False  True False]


In [57]:
print(a[a % 2 == 0])

[0 2 4 6 8]


In [58]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [59]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
print(a[idx])

[11 33 55 77 99]


In [62]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [63]:
a[[2,0,1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [64]:
# 넘파이의 자료형
import numpy as np

In [65]:
x = np.array([1,2,3])
print(x.dtype)

int64


In [66]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [67]:
x = np.array([1,2,3.0]) # 실수 우선적
x.dtype

dtype('float64')

In [68]:
print(x[0], x[1], x[2]) # 배열은 꼭 같은 타입의 데이터여야 한다.

1.0 2.0 3.0


In [70]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [71]:
print(x[0] + x[1])

3.0


In [72]:
x = np.array([1,2,3], dtype='U')
x.dtype

dtype('<U1')

In [73]:
x[0] + x[1]

'12'